import { MigrationInterface, QueryRunner } from "typeorm";

export class Phase6Update1774848310230 implements MigrationInterface {
    name = 'Phase6Update1774848310230'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_department_roles" DROP CONSTRAINT "FK_udr_role"`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" DROP CONSTRAINT "FK_udr_dept"`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" DROP CONSTRAINT "FK_udr_user"`);
        await queryRunner.query(`ALTER TABLE "tracking" DROP CONSTRAINT "FK_tracking_shipment"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_shipment"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_user"`);
        await queryRunner.query(`ALTER TABLE "shipment_logs" DROP CONSTRAINT "FK_logs_user"`);
        await queryRunner.query(`ALTER TABLE "shipment_logs" DROP CONSTRAINT "FK_logs_shipment"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_documents_user"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_documents_shipment"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_shipments_service"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_shipments_dept"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_shipments_user"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_notifications_user"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_role_permissions_permission"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_role_permissions_role"`);
        await queryRunner.query(`ALTER TABLE "shipment_collaborators" DROP CONSTRAINT "FK_collab_dept"`);
        await queryRunner.query(`ALTER TABLE "shipment_collaborators" DROP CONSTRAINT "FK_collab_shipment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_payment_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_reference"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_shipments_shipping_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_shipments_tracking_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_shipments_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_shipments_dept"`);
        await queryRunner.query(`ALTER TABLE "roles" RENAME COLUMN "description" TO "deleted_at"`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('DRAFT', 'SENT', 'PAID', 'PARTIAL', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_number" character varying NOT NULL, "shipment_id" uuid, "amount" numeric(14,2) NOT NULL, "tax" numeric(14,2) NOT NULL DEFAULT '0', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'DRAFT', "due_date" date, "notes" text, "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb" UNIQUE ("invoice_number"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d8f8d3788694e1b3f96c42c36f" ON "invoices" ("invoice_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_27a45b29d611d98978013a4ffc" ON "invoices" ("shipment_id") `);
        await queryRunner.query(`CREATE TABLE "document_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_id" uuid NOT NULL, "file_url" character varying NOT NULL, "file_key" character varying NOT NULL, "content_type" character varying NOT NULL, "version_number" integer NOT NULL, "uploader_id" uuid NOT NULL, "comment" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_baf26dab035c6d6fc433f9dc6a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac75577bca976d6d581b0f459b" ON "document_versions" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_252c68e367a018bce6861bc181" ON "document_versions" ("version_number") `);
        await queryRunner.query(`CREATE TYPE "public"."document_activity_action_enum" AS ENUM('UPLOADED', 'VIEWED', 'APPROVED', 'REJECTED', 'NEW_VERSION', 'DELETED')`);
        await queryRunner.query(`CREATE TABLE "document_activity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_id" uuid NOT NULL, "user_id" uuid NOT NULL, "action" "public"."document_activity_action_enum" NOT NULL, "comment" text, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cf311ccda75abcd6427464329dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e637cda90d710f1813a93a3c29" ON "document_activity" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_972d610704b332ff347409db33" ON "document_activity" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d39fd3c03ce5563831a71def14" ON "document_activity" ("timestamp") `);
        await queryRunner.query(`CREATE TYPE "public"."workflow_steps_status_enum" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "workflow_steps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shipment_id" uuid NOT NULL, "name" character varying NOT NULL, "step_order" integer NOT NULL, "status" "public"."workflow_steps_status_enum" NOT NULL DEFAULT 'PENDING', "department_id" character varying, "completed_by" character varying, "completed_at" TIMESTAMP, "comments" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b602e5ecb22943db11c96a7f31c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3414d3ea18da1ff7128ce0c94b" ON "workflow_steps" ("shipment_id") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" character varying NOT NULL, "resource" character varying NOT NULL, "resource_id" character varying, "user_id" uuid, "details" jsonb, "ip_address" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_62408b952557958fd12867cfeb" ON "audit_logs" ("resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd2726fd31b35443f2245b93ba" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`ALTER TABLE "user_department_roles" DROP CONSTRAINT "PK_user_department_roles_id"`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "departments" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "refresh_token" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "refresh_token_expires_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tracking" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tracking" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "invoice_id" uuid`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "current_version_id" character varying`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" ADD CONSTRAINT "PK_fdc6e68768e61c743afcb3c82f2" PRIMARY KEY ("user_id", "department_id", "role_id")`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_8866a3cfff96b8e17c2b204aae" ON "payments" ("payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_866ddee0e17d9385b4e3b86851" ON "payments" ("reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_563a5e248518c623eebd987d43" ON "payments" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d33a8898cfacff46c9f48d3f71" ON "shipments" ("shipping_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3684afc1ec2f81184f9a27405" ON "shipments" ("tracking_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a19baf6dd62cac42fbb40a518" ON "shipments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e7071986db4f8f1a3f894d6d5" ON "shipments" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_095de73246d77070f21e1e7f14" ON "shipment_collaborators" ("shipment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_88eb0bad7fdefc8fe811489a98" ON "shipment_collaborators" ("department_id") `);
        await queryRunner.query(`ALTER TABLE "user_department_roles" ADD CONSTRAINT "FK_9a665b97d3510d06894061a8db6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" ADD CONSTRAINT "FK_4090dad03cf5f43222f2442a3a5" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" ADD CONSTRAINT "FK_d84eaa384af8833c7137b93acc0" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracking" ADD CONSTRAINT "FK_552ca3cb0b0d6b9f89f3002c5ad" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_27a45b29d611d98978013a4ffc9" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_39a202af5d1dd1744458820ecb5" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_427785468fb7d2733f59e7d7d39" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_a849de550997f732685b44ae71a" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_563a5e248518c623eebd987d43e" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_logs" ADD CONSTRAINT "FK_2cee86b31834bf8a82b4dd11732" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_logs" ADD CONSTRAINT "FK_5b2075b40279b01635d39140aa5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_versions" ADD CONSTRAINT "FK_ac75577bca976d6d581b0f459b6" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_versions" ADD CONSTRAINT "FK_0cf94bc19cd0afb4a58326c43f8" FOREIGN KEY ("uploader_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_activity" ADD CONSTRAINT "FK_e637cda90d710f1813a93a3c297" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_activity" ADD CONSTRAINT "FK_972d610704b332ff347409db338" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_889a0f64bc98fe026477e527cfb" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_27c5610c1cd91c780af8ea85e38" FOREIGN KEY ("uploader_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_f1c9dcb7617e93104b846b45a2c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_5e7071986db4f8f1a3f894d6d5b" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_10624aeb790757f86d9f1b6e51d" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_steps" ADD CONSTRAINT "FK_3414d3ea18da1ff7128ce0c94b8" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "shipment_collaborators" ADD CONSTRAINT "FK_095de73246d77070f21e1e7f147" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "shipment_collaborators" ADD CONSTRAINT "FK_88eb0bad7fdefc8fe811489a98e" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "shipment_collaborators" DROP CONSTRAINT "FK_88eb0bad7fdefc8fe811489a98e"`);
        await queryRunner.query(`ALTER TABLE "shipment_collaborators" DROP CONSTRAINT "FK_095de73246d77070f21e1e7f147"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "workflow_steps" DROP CONSTRAINT "FK_3414d3ea18da1ff7128ce0c94b8"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_10624aeb790757f86d9f1b6e51d"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_5e7071986db4f8f1a3f894d6d5b"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_f1c9dcb7617e93104b846b45a2c"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_27c5610c1cd91c780af8ea85e38"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_889a0f64bc98fe026477e527cfb"`);
        await queryRunner.query(`ALTER TABLE "document_activity" DROP CONSTRAINT "FK_972d610704b332ff347409db338"`);
        await queryRunner.query(`ALTER TABLE "document_activity" DROP CONSTRAINT "FK_e637cda90d710f1813a93a3c297"`);
        await queryRunner.query(`ALTER TABLE "document_versions" DROP CONSTRAINT "FK_0cf94bc19cd0afb4a58326c43f8"`);
        await queryRunner.query(`ALTER TABLE "document_versions" DROP CONSTRAINT "FK_ac75577bca976d6d581b0f459b6"`);
        await queryRunner.query(`ALTER TABLE "shipment_logs" DROP CONSTRAINT "FK_5b2075b40279b01635d39140aa5"`);
        await queryRunner.query(`ALTER TABLE "shipment_logs" DROP CONSTRAINT "FK_2cee86b31834bf8a82b4dd11732"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_563a5e248518c623eebd987d43e"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_a849de550997f732685b44ae71a"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_427785468fb7d2733f59e7d7d39"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_39a202af5d1dd1744458820ecb5"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_27a45b29d611d98978013a4ffc9"`);
        await queryRunner.query(`ALTER TABLE "tracking" DROP CONSTRAINT "FK_552ca3cb0b0d6b9f89f3002c5ad"`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" DROP CONSTRAINT "FK_d84eaa384af8833c7137b93acc0"`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" DROP CONSTRAINT "FK_4090dad03cf5f43222f2442a3a5"`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" DROP CONSTRAINT "FK_9a665b97d3510d06894061a8db6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88eb0bad7fdefc8fe811489a98"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_095de73246d77070f21e1e7f14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e7071986db4f8f1a3f894d6d5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a19baf6dd62cac42fbb40a518"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3684afc1ec2f81184f9a27405"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d33a8898cfacff46c9f48d3f71"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_563a5e248518c623eebd987d43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_866ddee0e17d9385b4e3b86851"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8866a3cfff96b8e17c2b204aae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "deleted_at" text`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" DROP CONSTRAINT "PK_fdc6e68768e61c743afcb3c82f2"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "current_version_id"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "invoice_id"`);
        await queryRunner.query(`ALTER TABLE "tracking" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "tracking" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "refresh_token_expires_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "refresh_token"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" ADD CONSTRAINT "PK_user_department_roles_id" PRIMARY KEY ("id")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2726fd31b35443f2245b93ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_62408b952557958fd12867cfeb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3414d3ea18da1ff7128ce0c94b"`);
        await queryRunner.query(`DROP TABLE "workflow_steps"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_steps_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d39fd3c03ce5563831a71def14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_972d610704b332ff347409db33"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e637cda90d710f1813a93a3c29"`);
        await queryRunner.query(`DROP TABLE "document_activity"`);
        await queryRunner.query(`DROP TYPE "public"."document_activity_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_252c68e367a018bce6861bc181"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac75577bca976d6d581b0f459b"`);
        await queryRunner.query(`DROP TABLE "document_versions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27a45b29d611d98978013a4ffc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8f8d3788694e1b3f96c42c36f"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TABLE "roles" RENAME COLUMN "deleted_at" TO "description"`);
        await queryRunner.query(`CREATE INDEX "IDX_shipments_dept" ON "shipments" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_shipments_status" ON "shipments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_shipments_tracking_id" ON "shipments" ("tracking_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_shipments_shipping_id" ON "shipments" ("shipping_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_reference" ON "payments" ("reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_payment_id" ON "payments" ("payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_email" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "shipment_collaborators" ADD CONSTRAINT "FK_collab_shipment" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_collaborators" ADD CONSTRAINT "FK_collab_dept" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_role_permissions_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_role_permissions_permission" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_notifications_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_shipments_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_shipments_dept" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_shipments_service" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_documents_shipment" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_documents_user" FOREIGN KEY ("uploader_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_logs" ADD CONSTRAINT "FK_logs_shipment" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_logs" ADD CONSTRAINT "FK_logs_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_shipment" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracking" ADD CONSTRAINT "FK_tracking_shipment" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" ADD CONSTRAINT "FK_udr_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" ADD CONSTRAINT "FK_udr_dept" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" ADD CONSTRAINT "FK_udr_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
