import { MigrationInterface, QueryRunner } from "typeorm";

export class AddLastLoginToUser1776846288980 implements MigrationInterface {
    name = 'AddLastLoginToUser1776846288980'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_62408b952557958fd12867cfeb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2726fd31b35443f2245b93ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`CREATE TABLE "notification_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "emailShipmentStatus" boolean NOT NULL DEFAULT true, "emailAssignments" boolean NOT NULL DEFAULT true, "emailFinancial" boolean NOT NULL DEFAULT true, "inAppShipmentStatus" boolean NOT NULL DEFAULT true, "inAppAssignments" boolean NOT NULL DEFAULT true, "inAppFinancial" boolean NOT NULL DEFAULT true, "quiet_hours_enabled" boolean NOT NULL DEFAULT false, "quiet_hours_start" character varying, "quiet_hours_end" character varying, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_64c90edc7310c6be7c10c96f67" UNIQUE ("user_id"), CONSTRAINT "PK_e94e2b543f2f218ee68e4f4fad2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."messages_message_type_enum" AS ENUM('text', 'file')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sender_id" uuid NOT NULL, "recipient_id" uuid NOT NULL, "thread_id" character varying NOT NULL, "content" text NOT NULL, "message_type" "public"."messages_message_type_enum" NOT NULL DEFAULT 'text', "attachment_url" character varying, "attachment_name" character varying, "sent_at" TIMESTAMP NOT NULL DEFAULT now(), "read_at" TIMESTAMP, "is_deleted" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22133395bd13b970ccd0c34ab2" ON "messages" ("sender_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_566c3d68184e83d4307b86f85a" ON "messages" ("recipient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb3af7f695d50083e6523290d4" ON "messages" ("thread_id") `);
        await queryRunner.query(`ALTER TABLE "shipments" DROP COLUMN "actual_arrival_date"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "details"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "resource_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "resource"`);
        await queryRunner.query(`ALTER TABLE "departments" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "UQ_67e3d3ac46c34f0bfdf369771c1" UNIQUE ("email")`);
        await queryRunner.query(`CREATE TYPE "public"."departments_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`ALTER TABLE "departments" ADD "status" "public"."departments_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "departments" ADD "total_staff" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "departments" ADD "supervisor_id" uuid`);
        await queryRunner.query(`ALTER TABLE "departments" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_login" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_login_ip" character varying`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD "shipment_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD "internal_reference" character varying`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD "pickup_address" text`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD "delivery_address" text`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD "dimensions" jsonb DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD "expected_delivery_date" date`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD "actual_delivery_date" date`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD "internal_notes" text`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD "department_id" uuid`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "related_entity_type" character varying`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "related_entity_id" character varying`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "read_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "currency" character varying NOT NULL DEFAULT 'NGN'`);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_method_enum" AS ENUM('transfer', 'cash', 'card')`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "payment_method" "public"."payments_payment_method_enum"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "processed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "processed_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_id" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action_details" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "performed_by" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "department_id" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_agent" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "reason" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "performed_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."shipments_type_enum" RENAME TO "shipments_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."shipments_type_enum" AS ENUM('export', 'import')`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "type" TYPE "public"."shipments_type_enum" USING "type"::"text"::"public"."shipments_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."shipments_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."shipments_status_enum" RENAME TO "shipments_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."shipments_status_enum" AS ENUM('pending', 'in_transit', 'customs', 'delivered', 'on_hold', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "status" TYPE "public"."shipments_status_enum" USING "status"::"text"::"public"."shipments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."shipments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "client_name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "client_email" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "client_phone" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('status-update', 'system', 'alert', 'audit', 'message')`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'system'`);
        await queryRunner.query(`CREATE INDEX "IDX_8681da666ad9699d568b3e9106" ON "departments" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e7071986db4f8f1a3f894d6d5" ON "shipments" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d8796c5355aa510504b1ae7e40" ON "shipments" ("created_by_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ea9ba3dfb39050f831ee3be40d" ON "audit_logs" ("entity_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_85c204d8e47769ac183b32bf9c" ON "audit_logs" ("entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae97aac6d6d471b9d88cea1c97" ON "audit_logs" ("performed_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_53e3762649c716bff27b45b884" ON "audit_logs" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_19a17dd79fd3546ccc39d3da7e" ON "audit_logs" ("performed_at") `);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_0481ceb38715a7c60ad090f3d4d" FOREIGN KEY ("supervisor_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_c92e8cfee06c8e18abd172ea9e1" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_64c90edc7310c6be7c10c96f675" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_5e7071986db4f8f1a3f894d6d5b" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_d8796c5355aa510504b1ae7e40b" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_2ae10d0c6fc1db90429bc56955d" FOREIGN KEY ("processed_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_22133395bd13b970ccd0c34ab22" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_566c3d68184e83d4307b86f85ab" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_ae97aac6d6d471b9d88cea1c971" FOREIGN KEY ("performed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_ae97aac6d6d471b9d88cea1c971"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_566c3d68184e83d4307b86f85ab"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_22133395bd13b970ccd0c34ab22"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_2ae10d0c6fc1db90429bc56955d"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_d8796c5355aa510504b1ae7e40b"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_5e7071986db4f8f1a3f894d6d5b"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_64c90edc7310c6be7c10c96f675"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_c92e8cfee06c8e18abd172ea9e1"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_0481ceb38715a7c60ad090f3d4d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19a17dd79fd3546ccc39d3da7e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53e3762649c716bff27b45b884"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae97aac6d6d471b9d88cea1c97"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85c204d8e47769ac183b32bf9c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea9ba3dfb39050f831ee3be40d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8796c5355aa510504b1ae7e40"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e7071986db4f8f1a3f894d6d5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8681da666ad9699d568b3e9106"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "type" character varying NOT NULL DEFAULT 'SYSTEM'`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "client_phone" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "client_email" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "client_name" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."shipments_status_enum_old" AS ENUM('pending', 'in_transit', 'arrived', 'delivered', 'on_hold', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "status" TYPE "public"."shipments_status_enum_old" USING "status"::"text"::"public"."shipments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."shipments_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."shipments_status_enum_old" RENAME TO "shipments_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."shipments_type_enum_old" AS ENUM('air_freight', 'sea_freight')`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "type" TYPE "public"."shipments_type_enum_old" USING "type"::"text"::"public"."shipments_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."shipments_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."shipments_type_enum_old" RENAME TO "shipments_type_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "performed_at"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "reason"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "performed_by"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action_details"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_type"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "processed_by_id"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "processed_at"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "payment_method"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_method_enum"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "read_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "related_entity_id"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "related_entity_type"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP COLUMN "internal_notes"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP COLUMN "actual_delivery_date"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP COLUMN "expected_delivery_date"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP COLUMN "dimensions"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP COLUMN "delivery_address"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP COLUMN "pickup_address"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP COLUMN "internal_reference"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP COLUMN "shipment_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_login_ip"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_login"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP COLUMN "supervisor_id"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP COLUMN "total_staff"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."departments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "UQ_67e3d3ac46c34f0bfdf369771c1"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "resource" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "resource_id" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "details" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD "actual_arrival_date" date`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb3af7f695d50083e6523290d4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_566c3d68184e83d4307b86f85a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22133395bd13b970ccd0c34ab2"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."messages_message_type_enum"`);
        await queryRunner.query(`DROP TABLE "notification_preferences"`);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd2726fd31b35443f2245b93ba" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_62408b952557958fd12867cfeb" ON "audit_logs" ("resource_id") `);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
