import { MigrationInterface, QueryRunner } from "typeorm";

export class InitializeLogisticsSystem1776099762315 implements MigrationInterface {
    name = 'InitializeLogisticsSystem1776099762315'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "metadata" jsonb DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_8681da666ad9699d568b3e91064" UNIQUE ("name"), CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_scope_enum" AS ENUM('own', 'department', 'all')`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "resource" character varying NOT NULL, "action" character varying NOT NULL, "scope" "public"."permissions_scope_enum" NOT NULL DEFAULT 'own', "conditions" jsonb DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_department_roles" ("user_id" uuid NOT NULL, "department_id" uuid NOT NULL, "role_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fdc6e68768e61c743afcb3c82f2" PRIMARY KEY ("user_id", "department_id", "role_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('STAFF', 'ADMIN', 'SUPERADMIN')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "email" character varying NOT NULL, "password" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'STAFF', "phone_number" character varying, "outstanding_balance" numeric(12,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "refresh_token" character varying, "refresh_token_expires_at" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "tracking" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shipment_id" uuid NOT NULL, "checkpoint" character varying NOT NULL, "location" character varying, "status" character varying NOT NULL, "date" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c6d380f3abe9852840e5aff1439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."shipment_logs_visibility_enum" AS ENUM('public', 'internal')`);
        await queryRunner.query(`CREATE TABLE "shipment_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shipment_id" uuid NOT NULL, "user_id" uuid, "action" character varying, "previous_status" character varying, "new_status" character varying, "note" text, "email_sent" boolean NOT NULL DEFAULT false, "visibility" "public"."shipment_logs_visibility_enum" NOT NULL DEFAULT 'internal', "ip_address" character varying, "user_agent" character varying, "metadata" jsonb DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8850b9bd079729fd73a396468ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."shipments_type_enum" AS ENUM('air_freight', 'sea_freight')`);
        await queryRunner.query(`CREATE TYPE "public"."shipments_status_enum" AS ENUM('pending', 'in_transit', 'arrived', 'delivered', 'on_hold', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "shipments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tracking_number" character varying NOT NULL, "type" "public"."shipments_type_enum" NOT NULL, "status" "public"."shipments_status_enum" NOT NULL DEFAULT 'pending', "client_name" character varying NOT NULL, "client_email" character varying NOT NULL, "client_phone" character varying NOT NULL, "origin_country" character varying, "origin_city" character varying, "destination_country" character varying, "destination_city" character varying, "eta" date, "actual_arrival_date" date, "description" text, "weight_kg" numeric(10,2), "volume_cbm" numeric(10,2), "airline_or_vessel" character varying, "flight_or_voyage_number" character varying, "departure_date" date, "notes" text, "assigned_officer_id" uuid, "invoice_id" character varying, "customs_record_id" character varying, "is_deleted" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_e148d569550cfa0295ccf237066" UNIQUE ("tracking_number"), CONSTRAINT "PK_6deda4532ac542a93eab214b564" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e148d569550cfa0295ccf23706" ON "shipments" ("tracking_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a19baf6dd62cac42fbb40a518" ON "shipments" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."workflow_steps_status_enum" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "workflow_steps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shipment_id" uuid NOT NULL, "name" character varying NOT NULL, "step_order" integer NOT NULL, "status" "public"."workflow_steps_status_enum" NOT NULL DEFAULT 'PENDING', "department_id" character varying, "completed_by" character varying, "completed_at" TIMESTAMP, "comments" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b602e5ecb22943db11c96a7f31c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3414d3ea18da1ff7128ce0c94b" ON "workflow_steps" ("shipment_id") `);
        await queryRunner.query(`CREATE TABLE "services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "service_name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8403b383a9d6ef5b162a2de91c0" UNIQUE ("service_name"), CONSTRAINT "PK_ba2d347a3168a296416c6c5ccb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."locations_type_enum" AS ENUM('AIRPORT', 'SEAPORT')`);
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying NOT NULL, "country" character varying, "type" "public"."locations_type_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1c65ef243169e51b514c814eeae" UNIQUE ("code"), CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."customs_clearances_status_enum" AS ENUM('pending_documents', 'under_examination', 'duty_paid', 'released', 'exit_gate')`);
        await queryRunner.query(`CREATE TABLE "customs_clearances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shipment_id" uuid NOT NULL, "status" "public"."customs_clearances_status_enum" NOT NULL DEFAULT 'pending_documents', "clearing_agent_id" uuid, "remarks" text, "documents" jsonb, "released_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_cd0e97911f9f800c04de8c9c85" UNIQUE ("shipment_id"), CONSTRAINT "PK_f255eabdae3f1b154d286accb61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "action_url" character varying, "type" character varying NOT NULL DEFAULT 'SYSTEM', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payment_id" character varying NOT NULL, "reference" character varying NOT NULL, "amount" numeric(12,2) NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING', "paystack_access_code" character varying, "paystack_auth_url" character varying, "user_id" uuid NOT NULL, "shipment_id" uuid, "invoice_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8866a3cfff96b8e17c2b204aae0" UNIQUE ("payment_id"), CONSTRAINT "UQ_866ddee0e17d9385b4e3b86851d" UNIQUE ("reference"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8866a3cfff96b8e17c2b204aae" ON "payments" ("payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_866ddee0e17d9385b4e3b86851" ON "payments" ("reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_563a5e248518c623eebd987d43" ON "payments" ("invoice_id") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'sent', 'paid', 'overdue', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_number" character varying NOT NULL, "shipment_id" uuid, "client_name" character varying, "client_email" character varying, "items" jsonb NOT NULL DEFAULT '[]', "subtotal" numeric(12,2) NOT NULL, "tax_rate" numeric(5,2) NOT NULL DEFAULT '0', "tax_amount" numeric(12,2) NOT NULL, "total_amount" numeric(12,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'NGN', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'draft', "due_date" date, "paid_at" TIMESTAMP, "payment_method" character varying, "payment_reference" character varying, "pdf_url" text, "notes" text, "created_by" uuid NOT NULL, "is_deleted" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb" UNIQUE ("invoice_number"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d8f8d3788694e1b3f96c42c36f" ON "invoices" ("invoice_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_27a45b29d611d98978013a4ffc" ON "invoices" ("shipment_id") `);
        await queryRunner.query(`CREATE TYPE "public"."email_logs_status_enum" AS ENUM('sent', 'failed', 'bounced')`);
        await queryRunner.query(`CREATE TABLE "email_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shipment_id" uuid, "invoice_id" uuid, "recipient_email" character varying NOT NULL, "subject" character varying NOT NULL, "template_used" character varying, "status" "public"."email_logs_status_enum" NOT NULL DEFAULT 'sent', "sent_by" uuid, "error_message" text, "sent_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_999382218924e953a790d340571" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."document_activity_action_enum" AS ENUM('UPLOADED', 'VIEWED', 'APPROVED', 'REJECTED', 'NEW_VERSION', 'DELETED')`);
        await queryRunner.query(`CREATE TABLE "document_activity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_id" uuid NOT NULL, "user_id" uuid NOT NULL, "action" "public"."document_activity_action_enum" NOT NULL, "comment" text, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cf311ccda75abcd6427464329dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e637cda90d710f1813a93a3c29" ON "document_activity" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_972d610704b332ff347409db33" ON "document_activity" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d39fd3c03ce5563831a71def14" ON "document_activity" ("timestamp") `);
        await queryRunner.query(`CREATE TYPE "public"."documents_status_enum" AS ENUM('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TYPE "public"."documents_visibility_scope_enum" AS ENUM('GLOBAL', 'DEPARTMENT', 'PRIVATE')`);
        await queryRunner.query(`CREATE TABLE "documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "file_url" character varying NOT NULL, "file_key" character varying NOT NULL, "content_type" character varying NOT NULL, "document_type" character varying NOT NULL, "status" "public"."documents_status_enum" NOT NULL DEFAULT 'PENDING', "visibility_scope" "public"."documents_visibility_scope_enum" NOT NULL DEFAULT 'GLOBAL', "is_archived" boolean NOT NULL DEFAULT false, "admin_tags" jsonb DEFAULT '[]', "commit_message" text, "extracted_text" text, "metadata" jsonb DEFAULT '{}', "shipment_id" uuid, "department_id" uuid, "uploader_id" uuid NOT NULL, "current_version_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "document_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_id" uuid NOT NULL, "file_url" character varying NOT NULL, "file_key" character varying NOT NULL, "content_type" character varying NOT NULL, "version_number" integer NOT NULL, "uploader_id" uuid NOT NULL, "comment" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_baf26dab035c6d6fc433f9dc6a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac75577bca976d6d581b0f459b" ON "document_versions" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_252c68e367a018bce6861bc181" ON "document_versions" ("version_number") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" character varying NOT NULL, "resource" character varying NOT NULL, "resource_id" character varying, "user_id" uuid, "details" jsonb, "ip_address" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_62408b952557958fd12867cfeb" ON "audit_logs" ("resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd2726fd31b35443f2245b93ba" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "shipment_collaborators" ("shipment_id" uuid NOT NULL, "department_id" uuid NOT NULL, CONSTRAINT "PK_c23d81fe76ff085ca9b2a75284e" PRIMARY KEY ("shipment_id", "department_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_095de73246d77070f21e1e7f14" ON "shipment_collaborators" ("shipment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_88eb0bad7fdefc8fe811489a98" ON "shipment_collaborators" ("department_id") `);
        await queryRunner.query(`ALTER TABLE "user_department_roles" ADD CONSTRAINT "FK_9a665b97d3510d06894061a8db6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" ADD CONSTRAINT "FK_4090dad03cf5f43222f2442a3a5" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" ADD CONSTRAINT "FK_d84eaa384af8833c7137b93acc0" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracking" ADD CONSTRAINT "FK_552ca3cb0b0d6b9f89f3002c5ad" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_logs" ADD CONSTRAINT "FK_2cee86b31834bf8a82b4dd11732" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_logs" ADD CONSTRAINT "FK_5b2075b40279b01635d39140aa5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_0216d2c95591af884bb6a6b6f11" FOREIGN KEY ("assigned_officer_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_steps" ADD CONSTRAINT "FK_3414d3ea18da1ff7128ce0c94b8" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customs_clearances" ADD CONSTRAINT "FK_cd0e97911f9f800c04de8c9c853" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customs_clearances" ADD CONSTRAINT "FK_f5bedcb0c0669a1ba03d4b491c4" FOREIGN KEY ("clearing_agent_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_427785468fb7d2733f59e7d7d39" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_a849de550997f732685b44ae71a" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_563a5e248518c623eebd987d43e" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_27a45b29d611d98978013a4ffc9" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_39a202af5d1dd1744458820ecb5" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_logs" ADD CONSTRAINT "FK_c8cbbda20eb4df3e8662947cce0" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_logs" ADD CONSTRAINT "FK_11a84078c1aadc352a1b1111751" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_logs" ADD CONSTRAINT "FK_d3219f71910c9602362437b45ef" FOREIGN KEY ("sent_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_activity" ADD CONSTRAINT "FK_e637cda90d710f1813a93a3c297" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_activity" ADD CONSTRAINT "FK_972d610704b332ff347409db338" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_889a0f64bc98fe026477e527cfb" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_24a226d1434cd9a9748d5f11959" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_27c5610c1cd91c780af8ea85e38" FOREIGN KEY ("uploader_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_versions" ADD CONSTRAINT "FK_ac75577bca976d6d581b0f459b6" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_versions" ADD CONSTRAINT "FK_0cf94bc19cd0afb4a58326c43f8" FOREIGN KEY ("uploader_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "shipment_collaborators" ADD CONSTRAINT "FK_095de73246d77070f21e1e7f147" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "shipment_collaborators" ADD CONSTRAINT "FK_88eb0bad7fdefc8fe811489a98e" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "shipment_collaborators" DROP CONSTRAINT "FK_88eb0bad7fdefc8fe811489a98e"`);
        await queryRunner.query(`ALTER TABLE "shipment_collaborators" DROP CONSTRAINT "FK_095de73246d77070f21e1e7f147"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "document_versions" DROP CONSTRAINT "FK_0cf94bc19cd0afb4a58326c43f8"`);
        await queryRunner.query(`ALTER TABLE "document_versions" DROP CONSTRAINT "FK_ac75577bca976d6d581b0f459b6"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_27c5610c1cd91c780af8ea85e38"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_24a226d1434cd9a9748d5f11959"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_889a0f64bc98fe026477e527cfb"`);
        await queryRunner.query(`ALTER TABLE "document_activity" DROP CONSTRAINT "FK_972d610704b332ff347409db338"`);
        await queryRunner.query(`ALTER TABLE "document_activity" DROP CONSTRAINT "FK_e637cda90d710f1813a93a3c297"`);
        await queryRunner.query(`ALTER TABLE "email_logs" DROP CONSTRAINT "FK_d3219f71910c9602362437b45ef"`);
        await queryRunner.query(`ALTER TABLE "email_logs" DROP CONSTRAINT "FK_11a84078c1aadc352a1b1111751"`);
        await queryRunner.query(`ALTER TABLE "email_logs" DROP CONSTRAINT "FK_c8cbbda20eb4df3e8662947cce0"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_39a202af5d1dd1744458820ecb5"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_27a45b29d611d98978013a4ffc9"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_563a5e248518c623eebd987d43e"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_a849de550997f732685b44ae71a"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_427785468fb7d2733f59e7d7d39"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "customs_clearances" DROP CONSTRAINT "FK_f5bedcb0c0669a1ba03d4b491c4"`);
        await queryRunner.query(`ALTER TABLE "customs_clearances" DROP CONSTRAINT "FK_cd0e97911f9f800c04de8c9c853"`);
        await queryRunner.query(`ALTER TABLE "workflow_steps" DROP CONSTRAINT "FK_3414d3ea18da1ff7128ce0c94b8"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_0216d2c95591af884bb6a6b6f11"`);
        await queryRunner.query(`ALTER TABLE "shipment_logs" DROP CONSTRAINT "FK_5b2075b40279b01635d39140aa5"`);
        await queryRunner.query(`ALTER TABLE "shipment_logs" DROP CONSTRAINT "FK_2cee86b31834bf8a82b4dd11732"`);
        await queryRunner.query(`ALTER TABLE "tracking" DROP CONSTRAINT "FK_552ca3cb0b0d6b9f89f3002c5ad"`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" DROP CONSTRAINT "FK_d84eaa384af8833c7137b93acc0"`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" DROP CONSTRAINT "FK_4090dad03cf5f43222f2442a3a5"`);
        await queryRunner.query(`ALTER TABLE "user_department_roles" DROP CONSTRAINT "FK_9a665b97d3510d06894061a8db6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88eb0bad7fdefc8fe811489a98"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_095de73246d77070f21e1e7f14"`);
        await queryRunner.query(`DROP TABLE "shipment_collaborators"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2726fd31b35443f2245b93ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_62408b952557958fd12867cfeb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_252c68e367a018bce6861bc181"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac75577bca976d6d581b0f459b"`);
        await queryRunner.query(`DROP TABLE "document_versions"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP TYPE "public"."documents_visibility_scope_enum"`);
        await queryRunner.query(`DROP TYPE "public"."documents_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d39fd3c03ce5563831a71def14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_972d610704b332ff347409db33"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e637cda90d710f1813a93a3c29"`);
        await queryRunner.query(`DROP TABLE "document_activity"`);
        await queryRunner.query(`DROP TYPE "public"."document_activity_action_enum"`);
        await queryRunner.query(`DROP TABLE "email_logs"`);
        await queryRunner.query(`DROP TYPE "public"."email_logs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27a45b29d611d98978013a4ffc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8f8d3788694e1b3f96c42c36f"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_563a5e248518c623eebd987d43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_866ddee0e17d9385b4e3b86851"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8866a3cfff96b8e17c2b204aae"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "customs_clearances"`);
        await queryRunner.query(`DROP TYPE "public"."customs_clearances_status_enum"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP TYPE "public"."locations_type_enum"`);
        await queryRunner.query(`DROP TABLE "services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3414d3ea18da1ff7128ce0c94b"`);
        await queryRunner.query(`DROP TABLE "workflow_steps"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_steps_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a19baf6dd62cac42fbb40a518"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e148d569550cfa0295ccf23706"`);
        await queryRunner.query(`DROP TABLE "shipments"`);
        await queryRunner.query(`DROP TYPE "public"."shipments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."shipments_type_enum"`);
        await queryRunner.query(`DROP TABLE "shipment_logs"`);
        await queryRunner.query(`DROP TYPE "public"."shipment_logs_visibility_enum"`);
        await queryRunner.query(`DROP TABLE "tracking"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "user_department_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_scope_enum"`);
        await queryRunner.query(`DROP TABLE "departments"`);
    }

}
